name: grs

description: Grievance Redress System

publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  flutter_typeahead: ^4.8.0
  month_picker_dialog: ^4.0.0
  url_launcher: ^6.3.0
  url_launcher_ios: ^6.3.0
  pin_code_fields: ^8.0.1
  #hrk_batteries: ^0.9.1

  path: ^1.8.3
  get_storage: ^2.1.1
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  easy_localization: ^3.0.3
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  flutter_image_compress: ^2.1.0

  http: ^1.1.0
  get_it: ^7.6.4
  provider: ^6.1.1
  flutter_tts: ^3.8.3
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  import_sorter: ^4.6.0
  flutter_lints: ^3.0.1

import_sorter:
  emojis: true
  comments: false
  ignored_files:
    - \/test\/*

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/filled_icons/
    - assets/flags/
    - assets/fonts/
    - assets/icons/
    - assets/languages/
    - assets/logo/
    - assets/outline_icons/
    - assets/png_images/
    - assets/svg_images/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins-regular.ttf